### ISSUE TITLE
Saving issue related to address field? also from Thurs Swing

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#70] opened 2015-09-17 02:43 UTC
Follow up from Tuxedo (or maybe a new issue)
"Hi - We think the lockup issue may be related to the Address field. We noticed that sometimes the address field will change itself from our entry to something else so maybe it's a problem area in the software. Anyway, when there is something in the address field that the software doesn't like, that incident page locks up. lose the window, request to save the data, nothing is saved."

**Comment by wsanchez** [comment] 2017-09-26 21:36
Closing, can't reproduce now.

**Closed by wsanchez** 2017-09-26 21:36 UTC
