### ISSUE TITLE
"Save" incident update (Cafe Village Dissociative Participant) would not come back from "save" .  When closing window clicked on save.  When log checked incident not updated.

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#65] opened 2015-08-30 15:37 UTC
from sundancer, logged 2015-08-29 22:21

**Comment by wsanchez** [comment] 2017-09-26 21:33
Closing, can't reproduce now.

**Closed by wsanchez** 2017-09-26 21:33 UTC
