### ISSUE TITLE
Cannot add multiple incident reports to one incident ticket in 2016 instance

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#74] opened 2016-08-28 14:05 UTC
![screen shot 2016-08-28 at 6 59 46 am](https://cloud.githubusercontent.com/assets/13489518/18034252/10ce83f6-6ced-11e6-9498-f2c060a6ebf7.png)
In trying to create an incident to attach an unattached incident report to, I was unable to enter more than one incident report to the same incident ticket.  This might be a problem.

**Comment by wsanchez** [comment] 2017-09-26 21:35
Closing, can't reproduce now.

**Closed as completed by wsanchez** 2017-09-26 21:35 UTC
