### ISSUE TITLE
tried to make a new incident, clicked save, tried to close incident, asked if i wanted to save, i clicked yes, and window closed, but no new incident created

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#66] opened 2015-08-30 15:38 UTC
2015-08-29 22:53, Nekkid:
tried to make a new incident, clicked save, tried to close incident, asked if i wanted to save, i clicked yes, and window closed, but no new incident created

**Comment by wsanchez** [comment] 2017-09-26 21:33
Closing, can't reproduce now.

**Closed by wsanchez** 2017-09-26 21:33 UTC
